### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by ghost** [ArVdC/TimeManager#1]
[17:30:49 INFO]: This server is running Paper version git-Paper-1168 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[17:30:49 INFO]: Checking version, please wait...
[17:30:50 INFO]: You are 3 version(s) behind

```[TimeManager] Enabling TimeManager v1.0.2
[17:27:57] [Server thread/ERROR]: Error occurred while enabling TimeManager v1.0.2 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_131]
	at net.vdcraft.arvdc.timemanager.mainclass.ValuesConverter.KeepDecimalOfMcVersion(ValuesConverter.java:306) ~[?:?]
	at net.vdcraft.arvdc.timemanager.MainTM.onEnable(MainTM.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[core.jar:git-Paper-1168]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [core.jar:git-Paper-1168]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [core.jar:git-Paper-1168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[17:27:57] [Server thread/INFO]: [TimeManager] Disabling TimeManager v1.0.2
[17:27:57] [Server thread/ERROR]: Error occurred while disabling TimeManager v1.0.2 (Is it up to date?)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_131]
	at net.vdcraft.arvdc.timemanager.mainclass.ValuesConverter.KeepDecimalOfMcVersion(ValuesConverter.java:306) ~[?:?]
	at net.vdcraft.arvdc.timemanager.MainTM.onDisable(MainTM.java:270) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[core.jar:git-Paper-1168]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [core.jar:git-Paper-1168]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [core.jar:git-Paper-1168]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [core.jar:git-Paper-1168]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [core.jar:git-Paper-1168]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [core.jar:git-Paper-1168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by ArVdC** [comment]
Hi, I had  only tested with Spigot and Bukkit servers.
I've just fixed this, so it will be compatible with Paper for the next release. Probably in a few days.

**Comment by ArVdC** [comment]
Here is the new release : https://github.com/ArVdC/TimeManager/releases/tag/v1.1.0
I hope this will solve the problem.
I'll wait before closing this issue. Please, tell me if it works.
