### ISSUE TITLE
Plugin resets yaml to default at every restart

### ISSUE THREAD

**Issue by PumpkinPeasant** [ArVdC/TimeManager#2]
I know it could be buggy at 1.14.4. Plugin just do not allow me to set the options, it makes the option default every time i try to change it. 
`[WARNING] .... [TimeManager] Task #21 for TimeManager v1.2.0 generated an exception
java.lang.StringIndexOutOfBoundsException: null
at java.lang.String.charAt(String.java:1368) ~[?:1.8.0_212]
at net.vdcraft.arvdc.timemanager.mainclass.UpdateHandler.checkForUpdate(UpdateHandler.java:93) ~[?:?]
at net.vdcraft.arvdc.timemanager.mainclass.UpdateHandler$1.run(UpdateHandler.java:52) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]`

**Comment by ArVdC** [comment]
Hi, please try this updated version : [https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1](https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1) it should resolve this problem.
