### ISSUE TITLE
Probably my issue but i keep getting this error

### ISSUE THREAD

**Issue by efficiencyx** [ArVdC/TimeManager#27]
`[22:41:03 ERROR]: Error occurred while enabling TimeManager v1.8.2 (Is it up to date?)

java.lang.NoSuchMethodError: org/bukkit/configuration/file/FileConfigurationOptions.parseComments(Z)Lorg/bukkit/configuration/MemoryConfigurationOptions; (loaded from file:/home/container/cache/patched_1.17.1.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@308d6023) called from class net.vdcraft.arvdc.timemanager.mainclass.CfgFileHandler (loaded from file:/home/container/plugins/TimeManager-1.8.2.jar by PluginClassLoader{plugin=TimeManager v1.8.2, pluginEnabled=true, url=plugins/TimeManager-1.8.2.jar}).

at net.vdcraft.arvdc.timemanager.mainclass.CfgFileHandler.loadConfig(CfgFileHandler.java:18) ~[TimeManager-1.8.2.jar:?]

at net.vdcraft.arvdc.timemanager.MainTM.onEnable(MainTM.java:652) ~[TimeManager-1.8.2.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]

at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:428) ~[PlugManX (2).jar:?]

at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX (2).jar:?]

at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX (2).jar:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]

at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]

at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]

at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]

at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]

at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]

at java.lang.Thread.run(Unknown Source) ~[?:?]`
I updated from an old version 1.6.2 doing a backup, and removing the folder TimeManager.
i'm using Java 17 on Paper 1.17.1

**Comment by ArVdC** [comment]
I'm sorry but I can't reproduce this error. But I was only able to try with Java 18 and also I re-downloaded version 1.17.1 of Paper but it no longer works for me...
I have no other option than to try again to turn off the server and delete all Timemanager files in order to start with a completely clean installation or perhaps upgrade Java.
