### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by bananasmoothii** [ArVdC/TimeManager#3]
Hello,
Since I moved to 1.14.4, I always get this error:
```[10:45:34 WARN]: [TimeManager] Task #57 for TimeManager v1.2.0 generated an exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658) ~[?:1.8.0_242]
at net.vdcraft.arvdc.timemanager.mainclass.UpdateHandler.checkForUpdate(UpdateHandler.java:93) ~[?:?]
at net.vdcraft.arvdc.timemanager.mainclass.UpdateHandler$1.run(UpdateHandler.java:52) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
``` But everything is working fine. How to fix it ?

**Comment by ArVdC** [comment]
Hi, please try this updated version : [https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1](https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1) it should resolve this problem.

**Comment by bananasmoothii** [comment]
> Hi, please try this updated version : https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1 it should resolve this problem.

Yep, it does, thanks.

**Comment by ArVdC** [comment]
Ok, good.
Thank you for your feedback.

**Comment by ArVdC** [comment]
> > Hi, please try this updated version : https://github.com/ArVdC/TimeManager/releases/tag/v1.2.1 it should resolve this problem.
> 
> Yep, it does, thanks.

Ok, good.
Thank you for your feedback.
