### ISSUE TITLE
MySql and how to use UTC time shift

### ISSUE THREAD

**Issue by dongmashup2312** [ArVdC/TimeManager#32]
Help me with this please, this happened when I set "useMySql: 'true'" ... ! And how can I set UTC realtime in VietNam ? Thank you so much !!!

```
[20:22:44 INFO]: [TimeManager] Connection opening failure details:
[20:22:44 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[20:22:44 WARN]:
[20:22:44 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[20:22:44 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[20:22:44 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[20:22:44 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
[20:22:44 WARN]:        at TimeManager-1.9.1.jar//net.vdcraft.arvdc.timemanager.mainclass.SqlHandler.connectionToHostIsAvailable(SqlHandler.java:117)
[20:22:44 WARN]:        at TimeManager-1.9.1.jar//net.vdcraft.arvdc.timemanager.mainclass.SqlHandler.openTheConnectionIfPossible(SqlHandler.java:93)
[20:22:44 WARN]:        at TimeManager-1.9.1.jar//net.vdcraft.arvdc.timemanager.mainclass.SyncHandler.getOrSetInitialTickAndTime(SyncHandler.java:330)
[20:22:44 WARN]:        at TimeManager-1.9.1.jar//net.vdcraft.arvdc.timemanager.mainclass.SyncHandler$1.run(SyncHandler.java:22)
[20:22:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:22:44 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[20:22:44 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[20:22:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[20:22:44 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[20:22:44 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[20:22:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[20:22:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:22:44 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[20:22:44 WARN]:
[20:22:44 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[20:22:44 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[20:22:44 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[20:22:44 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[20:22:44 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
[20:22:44 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[20:22:44 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
[20:22:44 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
[20:22:44 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[20:22:44 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:121)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
[20:22:44 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
[20:22:44 WARN]:        ... 17 more
[20:22:44 WARN]: Caused by: java.net.ConnectException: Connection refused: connect
[20:22:44 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[20:22:44 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:589)
[20:22:44 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:578)
[20:22:44 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[20:22:44 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[20:22:44 WARN]:        at java.base/java.net.Socket.connect(Socket.java:751)
[20:22:44 WARN]:        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
[20:22:44 WARN]:        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[20:22:44 WARN]:        ... 20 more
[20:22:44 ERROR]: [TimeManager] Something prevented to establish a connection with provided host "localhost". Please check the config.yml file and set the debugMode to true to see error details.
```

**Comment by ArVdC** [comment]
Vietnam time zone is UTC+7, so :
`worldsList:`
`  yourWorld:`
`    start: +7`
`    daySpeed: 24.0`
`    nightSpeed: 24.0`

For SQL, the most likely is that the database fields are not configured correctly.
Have you entered all the data in it correctly? Is SQL active on your server? Please check the port, id, password etc.
Also note that if your server does not need to be synchronized with others, using a database is useless to you.
