### ISSUE TITLE
cmds bug

### ISSUE THREAD

**Issue by sorandno** [ArVdC/TimeManager#37]
If you set useCmds: 'true' on server version 1.21, an error will occur.1.21

```
[17:43:40 WARN]: [TimeManager] Task #4610 for TimeManager v1.10.0 generated an exception
java.time.temporal.UnsupportedTemporalTypeException: Unsupported unit: Seconds
	at java.base/java.time.LocalDate.until(LocalDate.java:1636) ~[?:?]
	at java.base/java.time.Duration.between(Duration.java:492) ~[?:?]
	at TimeManager-1.10.jar/net.vdcraft.arvdc.timemanager.mainclass.ValuesConverter.tickFromFormattedDate(ValuesConverter.java:526) ~[TimeManager-1.10.jar:?]
	at TimeManager-1.10.jar/net.vdcraft.arvdc.timemanager.mainclass.CmdsScheduler$1.run(CmdsScheduler.java:64) ~[TimeManager-1.10.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by ArVdC** [comment]
Please send me a copy of your cmds.yml file

**Comment by ArVdC** [comment]
I think I found what was wrong, please try this and let me know : [TimeManager v1.10.1](https://github.com/ArVdC/TimeManager/releases/tag/v1.10.1)

**Comment by sorandno** [comment]
There are no errors and it is working normally.

But it doesn't work for week.

day,month worked.

**Comment by ArVdC** [comment]
I made some changes, weekly repeat should now work.

**Comment by sorandno** [comment]
week also worked.
Thank you for your response!
