### ISSUE TITLE
SleepHandler$changeRequiredPercentage throws NullPointerException

### ISSUE THREAD

**Issue by Currypan1229** [ArVdC/TimeManager#39]
```
[14:14:12 ERROR]: Could not pass event PlayerQuitEvent to TimeManager v1.10.1-b
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
    at TimeManager-1.10.1-b.jar/net.vdcraft.arvdc.timemanager.mainclass.SleepHandler.changeRequiredPercentage(SleepHandler.java:682) ~[TimeManager-1.10.1-b.jar:?]
    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2233-0d6766e]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:613) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:597) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2171) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2138) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.network.Connection.handleDisconnection(Connection.java:899) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Currypan1229** [comment]
throws when players join/quit server or change worlds

**Comment by ArVdC** [comment]
II tried to reproduce the error but I couldn't.
For this error to occur, the `nightSkipRequiredPlayers` node in the config file would have to be null.
However, when the config.yml file loads, the wrong or missing values ​​are automatically replaced by a default value of 100%.
Maybe you should try deleting your config file and try again?
Also, consider using version 1.10.1 of the plugin, even if it doesn't differ much from the beta.

**Comment by ArVdC** [comment]
It's fixed : [1.10.2 corrective patch](https://github.com/ArVdC/TimeManager/releases/tag/v1.10.2)
